/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.madhouse.ssp.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class DSPRequest extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1710351207448413079L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DSPRequest\",\"namespace\":\"com.madhouse.ssp.avro\",\"fields\":[{\"name\":\"id\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"impid\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"adtype\",\"type\":\"int\"},{\"name\":\"layout\",\"type\":\"int\"},{\"name\":\"tagid\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"dealid\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"test\",\"type\":\"int\"},{\"name\":\"bidfloor\",\"type\":\"int\",\"default\":0},{\"name\":\"bidtype\",\"type\":\"int\",\"default\":1},{\"name\":\"tmax\",\"type\":\"int\",\"default\":120}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<DSPRequest> ENCODER =
      new BinaryMessageEncoder<DSPRequest>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DSPRequest> DECODER =
      new BinaryMessageDecoder<DSPRequest>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<DSPRequest> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<DSPRequest> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<DSPRequest>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this DSPRequest to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a DSPRequest from a ByteBuffer. */
  public static DSPRequest fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String id;
  @Deprecated public java.lang.String impid;
  @Deprecated public int adtype;
  @Deprecated public int layout;
  @Deprecated public java.lang.String tagid;
  @Deprecated public java.lang.String dealid;
  @Deprecated public int test;
  @Deprecated public int bidfloor;
  @Deprecated public int bidtype;
  @Deprecated public int tmax;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DSPRequest() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param impid The new value for impid
   * @param adtype The new value for adtype
   * @param layout The new value for layout
   * @param tagid The new value for tagid
   * @param dealid The new value for dealid
   * @param test The new value for test
   * @param bidfloor The new value for bidfloor
   * @param bidtype The new value for bidtype
   * @param tmax The new value for tmax
   */
  public DSPRequest(java.lang.String id, java.lang.String impid, java.lang.Integer adtype, java.lang.Integer layout, java.lang.String tagid, java.lang.String dealid, java.lang.Integer test, java.lang.Integer bidfloor, java.lang.Integer bidtype, java.lang.Integer tmax) {
    this.id = id;
    this.impid = impid;
    this.adtype = adtype;
    this.layout = layout;
    this.tagid = tagid;
    this.dealid = dealid;
    this.test = test;
    this.bidfloor = bidfloor;
    this.bidtype = bidtype;
    this.tmax = tmax;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return impid;
    case 2: return adtype;
    case 3: return layout;
    case 4: return tagid;
    case 5: return dealid;
    case 6: return test;
    case 7: return bidfloor;
    case 8: return bidtype;
    case 9: return tmax;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.String)value$; break;
    case 1: impid = (java.lang.String)value$; break;
    case 2: adtype = (java.lang.Integer)value$; break;
    case 3: layout = (java.lang.Integer)value$; break;
    case 4: tagid = (java.lang.String)value$; break;
    case 5: dealid = (java.lang.String)value$; break;
    case 6: test = (java.lang.Integer)value$; break;
    case 7: bidfloor = (java.lang.Integer)value$; break;
    case 8: bidtype = (java.lang.Integer)value$; break;
    case 9: tmax = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.String getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'impid' field.
   * @return The value of the 'impid' field.
   */
  public java.lang.String getImpid() {
    return impid;
  }

  /**
   * Sets the value of the 'impid' field.
   * @param value the value to set.
   */
  public void setImpid(java.lang.String value) {
    this.impid = value;
  }

  /**
   * Gets the value of the 'adtype' field.
   * @return The value of the 'adtype' field.
   */
  public java.lang.Integer getAdtype() {
    return adtype;
  }

  /**
   * Sets the value of the 'adtype' field.
   * @param value the value to set.
   */
  public void setAdtype(java.lang.Integer value) {
    this.adtype = value;
  }

  /**
   * Gets the value of the 'layout' field.
   * @return The value of the 'layout' field.
   */
  public java.lang.Integer getLayout() {
    return layout;
  }

  /**
   * Sets the value of the 'layout' field.
   * @param value the value to set.
   */
  public void setLayout(java.lang.Integer value) {
    this.layout = value;
  }

  /**
   * Gets the value of the 'tagid' field.
   * @return The value of the 'tagid' field.
   */
  public java.lang.String getTagid() {
    return tagid;
  }

  /**
   * Sets the value of the 'tagid' field.
   * @param value the value to set.
   */
  public void setTagid(java.lang.String value) {
    this.tagid = value;
  }

  /**
   * Gets the value of the 'dealid' field.
   * @return The value of the 'dealid' field.
   */
  public java.lang.String getDealid() {
    return dealid;
  }

  /**
   * Sets the value of the 'dealid' field.
   * @param value the value to set.
   */
  public void setDealid(java.lang.String value) {
    this.dealid = value;
  }

  /**
   * Gets the value of the 'test' field.
   * @return The value of the 'test' field.
   */
  public java.lang.Integer getTest() {
    return test;
  }

  /**
   * Sets the value of the 'test' field.
   * @param value the value to set.
   */
  public void setTest(java.lang.Integer value) {
    this.test = value;
  }

  /**
   * Gets the value of the 'bidfloor' field.
   * @return The value of the 'bidfloor' field.
   */
  public java.lang.Integer getBidfloor() {
    return bidfloor;
  }

  /**
   * Sets the value of the 'bidfloor' field.
   * @param value the value to set.
   */
  public void setBidfloor(java.lang.Integer value) {
    this.bidfloor = value;
  }

  /**
   * Gets the value of the 'bidtype' field.
   * @return The value of the 'bidtype' field.
   */
  public java.lang.Integer getBidtype() {
    return bidtype;
  }

  /**
   * Sets the value of the 'bidtype' field.
   * @param value the value to set.
   */
  public void setBidtype(java.lang.Integer value) {
    this.bidtype = value;
  }

  /**
   * Gets the value of the 'tmax' field.
   * @return The value of the 'tmax' field.
   */
  public java.lang.Integer getTmax() {
    return tmax;
  }

  /**
   * Sets the value of the 'tmax' field.
   * @param value the value to set.
   */
  public void setTmax(java.lang.Integer value) {
    this.tmax = value;
  }

  /**
   * Creates a new DSPRequest RecordBuilder.
   * @return A new DSPRequest RecordBuilder
   */
  public static com.madhouse.ssp.avro.DSPRequest.Builder newBuilder() {
    return new com.madhouse.ssp.avro.DSPRequest.Builder();
  }

  /**
   * Creates a new DSPRequest RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DSPRequest RecordBuilder
   */
  public static com.madhouse.ssp.avro.DSPRequest.Builder newBuilder(com.madhouse.ssp.avro.DSPRequest.Builder other) {
    return new com.madhouse.ssp.avro.DSPRequest.Builder(other);
  }

  /**
   * Creates a new DSPRequest RecordBuilder by copying an existing DSPRequest instance.
   * @param other The existing instance to copy.
   * @return A new DSPRequest RecordBuilder
   */
  public static com.madhouse.ssp.avro.DSPRequest.Builder newBuilder(com.madhouse.ssp.avro.DSPRequest other) {
    return new com.madhouse.ssp.avro.DSPRequest.Builder(other);
  }

  /**
   * RecordBuilder for DSPRequest instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DSPRequest>
    implements org.apache.avro.data.RecordBuilder<DSPRequest> {

    private java.lang.String id;
    private java.lang.String impid;
    private int adtype;
    private int layout;
    private java.lang.String tagid;
    private java.lang.String dealid;
    private int test;
    private int bidfloor;
    private int bidtype;
    private int tmax;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.madhouse.ssp.avro.DSPRequest.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.impid)) {
        this.impid = data().deepCopy(fields()[1].schema(), other.impid);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.adtype)) {
        this.adtype = data().deepCopy(fields()[2].schema(), other.adtype);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.layout)) {
        this.layout = data().deepCopy(fields()[3].schema(), other.layout);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.tagid)) {
        this.tagid = data().deepCopy(fields()[4].schema(), other.tagid);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.dealid)) {
        this.dealid = data().deepCopy(fields()[5].schema(), other.dealid);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.test)) {
        this.test = data().deepCopy(fields()[6].schema(), other.test);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.bidfloor)) {
        this.bidfloor = data().deepCopy(fields()[7].schema(), other.bidfloor);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.bidtype)) {
        this.bidtype = data().deepCopy(fields()[8].schema(), other.bidtype);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.tmax)) {
        this.tmax = data().deepCopy(fields()[9].schema(), other.tmax);
        fieldSetFlags()[9] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing DSPRequest instance
     * @param other The existing instance to copy.
     */
    private Builder(com.madhouse.ssp.avro.DSPRequest other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.impid)) {
        this.impid = data().deepCopy(fields()[1].schema(), other.impid);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.adtype)) {
        this.adtype = data().deepCopy(fields()[2].schema(), other.adtype);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.layout)) {
        this.layout = data().deepCopy(fields()[3].schema(), other.layout);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.tagid)) {
        this.tagid = data().deepCopy(fields()[4].schema(), other.tagid);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.dealid)) {
        this.dealid = data().deepCopy(fields()[5].schema(), other.dealid);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.test)) {
        this.test = data().deepCopy(fields()[6].schema(), other.test);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.bidfloor)) {
        this.bidfloor = data().deepCopy(fields()[7].schema(), other.bidfloor);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.bidtype)) {
        this.bidtype = data().deepCopy(fields()[8].schema(), other.bidtype);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.tmax)) {
        this.tmax = data().deepCopy(fields()[9].schema(), other.tmax);
        fieldSetFlags()[9] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.String getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.madhouse.ssp.avro.DSPRequest.Builder setId(java.lang.String value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.madhouse.ssp.avro.DSPRequest.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'impid' field.
      * @return The value.
      */
    public java.lang.String getImpid() {
      return impid;
    }

    /**
      * Sets the value of the 'impid' field.
      * @param value The value of 'impid'.
      * @return This builder.
      */
    public com.madhouse.ssp.avro.DSPRequest.Builder setImpid(java.lang.String value) {
      validate(fields()[1], value);
      this.impid = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'impid' field has been set.
      * @return True if the 'impid' field has been set, false otherwise.
      */
    public boolean hasImpid() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'impid' field.
      * @return This builder.
      */
    public com.madhouse.ssp.avro.DSPRequest.Builder clearImpid() {
      impid = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'adtype' field.
      * @return The value.
      */
    public java.lang.Integer getAdtype() {
      return adtype;
    }

    /**
      * Sets the value of the 'adtype' field.
      * @param value The value of 'adtype'.
      * @return This builder.
      */
    public com.madhouse.ssp.avro.DSPRequest.Builder setAdtype(int value) {
      validate(fields()[2], value);
      this.adtype = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'adtype' field has been set.
      * @return True if the 'adtype' field has been set, false otherwise.
      */
    public boolean hasAdtype() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'adtype' field.
      * @return This builder.
      */
    public com.madhouse.ssp.avro.DSPRequest.Builder clearAdtype() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'layout' field.
      * @return The value.
      */
    public java.lang.Integer getLayout() {
      return layout;
    }

    /**
      * Sets the value of the 'layout' field.
      * @param value The value of 'layout'.
      * @return This builder.
      */
    public com.madhouse.ssp.avro.DSPRequest.Builder setLayout(int value) {
      validate(fields()[3], value);
      this.layout = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'layout' field has been set.
      * @return True if the 'layout' field has been set, false otherwise.
      */
    public boolean hasLayout() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'layout' field.
      * @return This builder.
      */
    public com.madhouse.ssp.avro.DSPRequest.Builder clearLayout() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'tagid' field.
      * @return The value.
      */
    public java.lang.String getTagid() {
      return tagid;
    }

    /**
      * Sets the value of the 'tagid' field.
      * @param value The value of 'tagid'.
      * @return This builder.
      */
    public com.madhouse.ssp.avro.DSPRequest.Builder setTagid(java.lang.String value) {
      validate(fields()[4], value);
      this.tagid = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'tagid' field has been set.
      * @return True if the 'tagid' field has been set, false otherwise.
      */
    public boolean hasTagid() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'tagid' field.
      * @return This builder.
      */
    public com.madhouse.ssp.avro.DSPRequest.Builder clearTagid() {
      tagid = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'dealid' field.
      * @return The value.
      */
    public java.lang.String getDealid() {
      return dealid;
    }

    /**
      * Sets the value of the 'dealid' field.
      * @param value The value of 'dealid'.
      * @return This builder.
      */
    public com.madhouse.ssp.avro.DSPRequest.Builder setDealid(java.lang.String value) {
      validate(fields()[5], value);
      this.dealid = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'dealid' field has been set.
      * @return True if the 'dealid' field has been set, false otherwise.
      */
    public boolean hasDealid() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'dealid' field.
      * @return This builder.
      */
    public com.madhouse.ssp.avro.DSPRequest.Builder clearDealid() {
      dealid = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'test' field.
      * @return The value.
      */
    public java.lang.Integer getTest() {
      return test;
    }

    /**
      * Sets the value of the 'test' field.
      * @param value The value of 'test'.
      * @return This builder.
      */
    public com.madhouse.ssp.avro.DSPRequest.Builder setTest(int value) {
      validate(fields()[6], value);
      this.test = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'test' field has been set.
      * @return True if the 'test' field has been set, false otherwise.
      */
    public boolean hasTest() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'test' field.
      * @return This builder.
      */
    public com.madhouse.ssp.avro.DSPRequest.Builder clearTest() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'bidfloor' field.
      * @return The value.
      */
    public java.lang.Integer getBidfloor() {
      return bidfloor;
    }

    /**
      * Sets the value of the 'bidfloor' field.
      * @param value The value of 'bidfloor'.
      * @return This builder.
      */
    public com.madhouse.ssp.avro.DSPRequest.Builder setBidfloor(int value) {
      validate(fields()[7], value);
      this.bidfloor = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'bidfloor' field has been set.
      * @return True if the 'bidfloor' field has been set, false otherwise.
      */
    public boolean hasBidfloor() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'bidfloor' field.
      * @return This builder.
      */
    public com.madhouse.ssp.avro.DSPRequest.Builder clearBidfloor() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'bidtype' field.
      * @return The value.
      */
    public java.lang.Integer getBidtype() {
      return bidtype;
    }

    /**
      * Sets the value of the 'bidtype' field.
      * @param value The value of 'bidtype'.
      * @return This builder.
      */
    public com.madhouse.ssp.avro.DSPRequest.Builder setBidtype(int value) {
      validate(fields()[8], value);
      this.bidtype = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'bidtype' field has been set.
      * @return True if the 'bidtype' field has been set, false otherwise.
      */
    public boolean hasBidtype() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'bidtype' field.
      * @return This builder.
      */
    public com.madhouse.ssp.avro.DSPRequest.Builder clearBidtype() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'tmax' field.
      * @return The value.
      */
    public java.lang.Integer getTmax() {
      return tmax;
    }

    /**
      * Sets the value of the 'tmax' field.
      * @param value The value of 'tmax'.
      * @return This builder.
      */
    public com.madhouse.ssp.avro.DSPRequest.Builder setTmax(int value) {
      validate(fields()[9], value);
      this.tmax = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'tmax' field has been set.
      * @return True if the 'tmax' field has been set, false otherwise.
      */
    public boolean hasTmax() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'tmax' field.
      * @return This builder.
      */
    public com.madhouse.ssp.avro.DSPRequest.Builder clearTmax() {
      fieldSetFlags()[9] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DSPRequest build() {
      try {
        DSPRequest record = new DSPRequest();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.String) defaultValue(fields()[0]);
        record.impid = fieldSetFlags()[1] ? this.impid : (java.lang.String) defaultValue(fields()[1]);
        record.adtype = fieldSetFlags()[2] ? this.adtype : (java.lang.Integer) defaultValue(fields()[2]);
        record.layout = fieldSetFlags()[3] ? this.layout : (java.lang.Integer) defaultValue(fields()[3]);
        record.tagid = fieldSetFlags()[4] ? this.tagid : (java.lang.String) defaultValue(fields()[4]);
        record.dealid = fieldSetFlags()[5] ? this.dealid : (java.lang.String) defaultValue(fields()[5]);
        record.test = fieldSetFlags()[6] ? this.test : (java.lang.Integer) defaultValue(fields()[6]);
        record.bidfloor = fieldSetFlags()[7] ? this.bidfloor : (java.lang.Integer) defaultValue(fields()[7]);
        record.bidtype = fieldSetFlags()[8] ? this.bidtype : (java.lang.Integer) defaultValue(fields()[8]);
        record.tmax = fieldSetFlags()[9] ? this.tmax : (java.lang.Integer) defaultValue(fields()[9]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DSPRequest>
    WRITER$ = (org.apache.avro.io.DatumWriter<DSPRequest>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DSPRequest>
    READER$ = (org.apache.avro.io.DatumReader<DSPRequest>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
